baseURL = 'https://omahadsaadmin.github.io/ben-larson-ia-campaign-hugo-website/'
languageCode = 'en-us'
title = 'Benjamin Larson for City Council'
theme = 'hugo-theme-cleanwhite-master'
header_image = '/images/BenLarson.webp'